# Generated by Django 3.0.4 on 2020-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('PubDate', models.DateField()),
                ('Text', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
