# Generated by Django 3.0.4 on 2020-04-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='PubDate',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
