# Generated by Django 3.0.4 on 2020-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
