# Generated by Django 3.0.4 on 2020-04-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_remove_blogpost_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
