# Generated by Django 3.0.7 on 2020-06-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
