# Generated by Django 3.0.7 on 2020-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20200623_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainername',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
