# Generated by Django 3.0.7 on 2020-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20200623_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainername',
            field=models.CharField(blank=True, default='anonymous', max_length=40, null=True),
        ),
    ]
