# Generated by Django 3.0.7 on 2020-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20200623_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainername',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
