# Generated by Django 3.0.7 on 2020-06-23 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0007_auto_20200623_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainer',
            new_name='Profile',
        ),
    ]
