# Generated by Django 3.0.7 on 2020-07-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0010_auto_20200625_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('pokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainer.Pokemon')),
            ],
            bases=('trainer.pokemon',),
        ),
        migrations.CreateModel(
            name='Hunters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ManyToManyField(to='trainer.Pokemon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Hunters', related_query_name='Hunters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
