# Generated by Django 3.0.6 on 2020-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=40)),
                ('subcountry', models.CharField(max_length=40)),
                ('geonameid', models.CharField(max_length=40)),
            ],
        ),
    ]
