# Generated by Django 3.0.6 on 2020-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='subcountry',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
