# Generated by Django 3.0.3 on 2020-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_auto_20200213_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Lijn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
