# Generated by Django 3.0.3 on 2020-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_auto_20200213_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('Typenummer', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Image', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
