# Generated by Django 3.1.2 on 2020-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(blank=True, max_length=40)),
                ('authors', models.CharField(blank=True, max_length=150)),
                ('original_publication_year', models.IntegerField(blank=True)),
                ('original_title', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('average_rating', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('image_url', models.URLField()),
                ('small_image_url', models.URLField()),
                ('romance', models.IntegerField()),
                ('scifi', models.IntegerField()),
                ('adventure', models.IntegerField()),
                ('action', models.IntegerField()),
                ('drama', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('mystery', models.IntegerField()),
                ('supernatural', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('historical', models.IntegerField()),
                ('realistic', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('war', models.IntegerField()),
                ('manga_anime', models.IntegerField()),
                ('sport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('romance', models.IntegerField()),
                ('scifi', models.IntegerField()),
                ('adventure', models.IntegerField()),
                ('action', models.IntegerField()),
                ('drama', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('mystery', models.IntegerField()),
                ('supernatural', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('historical', models.IntegerField()),
                ('realistic', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('war', models.IntegerField()),
                ('manga_anime', models.IntegerField()),
                ('sport', models.IntegerField()),
            ],
        ),
    ]
